sudo: required
dist: trusty
language: php

php: 
  - 7.1

  branches:
    only:
      - master #-> Staging Server
      - develop #-> DevServer

     #sebelum melakukan atau eksekusi script
     #install kebetuhan os, ex: mod-php, dll 
    before_install:
    

      #pre eksekusi
      #testing dll
      #build
    before_script:
      - cp .env.travis .env
      - composer install --no-interaction
      - php artisan key:generate

      #main eksekusi
      #jalankan testing
    script:
      - ./vendor/bin/phpunit





